# Generated by Django 2.0.7 on 2018-09-13 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20180912_2136'),
        ('tasks', '0003_assessmenttaskinstance_assessment_task_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentTaskInstance',
            new_name='AssessmentTask',
        ),
        migrations.RenameModel(
            old_name='MedicationTaskInstance',
            new_name='MedicationTask',
        ),
        migrations.RenameModel(
            old_name='PatientTaskInstance',
            new_name='PatientTask',
        ),
        migrations.RenameModel(
            old_name='SymptomTaskInstance',
            new_name='SymptomTask',
        ),
        migrations.RenameModel(
            old_name='TeamTaskInstance',
            new_name='TeamTask',
        ),
        migrations.AlterModelOptions(
            name='medicationtasktemplate',
            options={'ordering': ('plan', 'patient_medication')},
        ),
        migrations.AlterModelOptions(
            name='patienttask',
            options={'ordering': ('plan', 'patient_task_template', 'due_datetime')},
        ),
        migrations.AlterModelOptions(
            name='teamtask',
            options={'ordering': ('plan', 'team_task_template', 'due_datetime')},
        ),
        migrations.RenameField(
            model_name='assessmentresponse',
            old_name='assessment_task_instance',
            new_name='assessment_task',
        ),
        migrations.RenameField(
            model_name='assessmenttask',
            old_name='plan_instance',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='medicationtasktemplate',
            old_name='plan_instance',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='patienttask',
            old_name='plan_instance',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='symptomrating',
            old_name='symptom_task_instance',
            new_name='symptom_task',
        ),
        migrations.RenameField(
            model_name='symptomtask',
            old_name='plan_instance',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='teamtask',
            old_name='plan_instance',
            new_name='plan',
        ),
    ]
