# Generated by Django 2.0.7 on 2018-09-18 02:40

from django.db import migrations


def assign_is_complete_to_assessment_tasks(apps, schema_editor):
    """
    This migration will run through all questions and responses to all
    AssessmentTask and set the `is_complete` field of
    :model:`tasks.AssesmentTask` to True if all its questions have its
    corresponding response.
    """
    AssessmentTask = apps.get_model('tasks', 'AssessmentTask')

    for task in AssessmentTask.objects.all():
        value = True
        questions = task.assessment_task_template.assessmentquestion_set\
            .values_list('id', flat=True).distinct()
        responses = task.assessmentresponse_set.values_list(
            'assessment_question', flat=True).distinct()

        if questions.exists():
            for question_id in questions:
                if question_id not in responses:
                    value = False
                    break
        else:
            value = False

        if value:
            task.is_complete = value
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180917_2034'),
    ]

    operations = [
        migrations.RunPython(assign_is_complete_to_assessment_tasks)
    ]
