# Generated by Django 2.0.7 on 2018-09-20 05:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_goalcomment'),
        ('tasks', '0011_auto_20180918_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_on_day', models.IntegerField()),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='once', max_length=20)),
                ('repeat_amount', models.IntegerField(default=-1, help_text="\n        Only matters if frequency is not 'once'.\n        If it is below 0, it will repeat until the plan ends\n        ")),
                ('appear_time', models.TimeField()),
                ('due_time', models.TimeField()),
                ('name', models.CharField(max_length=254)),
                ('plan_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_templates', to='plans.CarePlanTemplate')),
            ],
            options={
                'verbose_name': 'Vital Task Template',
                'verbose_name_plural': 'Vital Task Templates',
            },
        ),
    ]
