# Generated by Django 2.0.7 on 2018-09-20 06:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_vitaltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=255)),
                ('answer_type', models.CharField(max_length=128)),
                ('vital_task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tasks.VitalTaskTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
