# Generated by Django 2.0.7 on 2018-09-24 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_vitalresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitaltasktemplate',
            options={'ordering': ('name',), 'verbose_name': 'Vital Task Template', 'verbose_name_plural': 'Vital Task Templates'},
        ),
        migrations.AlterField(
            model_name='symptomrating',
            name='symptom_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tasks.SymptomTask'),
        ),
    ]
