# Generated by Django 2.0.7 on 2018-10-09 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20180925_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationtask',
            name='medication_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_tasks', to='tasks.MedicationTaskTemplate'),
        ),
    ]
