# Generated by Django 2.0.7 on 2018-10-20 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20181008_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttask',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_tasks', to='plans.CarePlan'),
        ),
    ]
