# Generated by Django 2.0.7 on 2018-10-24 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20181020_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomrating',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptomrating',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
