# Generated by Django 2.0.7 on 2019-01-25 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20181023_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresponse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vitalresponse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalresponse',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
