# Generated by Django 2.0.7 on 2019-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20190124_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentquestion',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='vitalquestion',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vitalquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
