# Generated by Django 2.0.7 on 2019-03-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20190228_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttask',
            name='assessment_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_tasks', to='tasks.AssessmentTaskTemplate'),
        ),
    ]
