# Generated by Django 2.0.7 on 2019-03-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20190228_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitaltasktemplate',
            name='instructions',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='vitaltasktemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
