# Generated by Django 2.0.7 on 2019-03-02 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20190301_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomrating',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.Symptom'),
        ),
    ]
