# Generated by Django 2.0.7 on 2019-03-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20190306_1352'),
        ('tasks', '0026_auto_20190301_2056'),
    ]

    operations = [
    ]
