# Generated by Django 2.0.7 on 2019-03-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_employeerole'),
        ('tasks', '0027_merge_20190311_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomtasktemplate',
            name='default_symptoms',
            field=models.ManyToManyField(null=True, related_name='task_templates', to='core.Symptom'),
        ),
        migrations.AddField(
            model_name='symptomtasktemplate',
            name='name',
            field=models.CharField(default='Symptom Task Template Name', max_length=255),
            preserve_default=False,
        ),
    ]
