# Generated by Django 2.0.7 on 2019-03-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20190327_2010'),
        ('tasks', '0028_auto_20190326_1736'),
    ]

    operations = [
    ]
