# Generated by Django 2.0.7 on 2019-03-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_employeerole'),
        ('tasks', '0028_auto_20190327_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtasktemplate',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='team_task_templates', to='core.ProviderRole'),
        ),
    ]
