# Generated by Django 2.0.7 on 2019-03-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_teamtasktemplate_roles'),
        ('tasks', '0029_merge_20190328_1244'),
    ]

    operations = [
    ]
