# Generated by Django 2.0.7 on 2019-03-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_merge_20190328_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtasktemplate',
            name='role',
        ),
    ]
