# Generated by Django 2.0.7 on 2019-03-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_remove_teamtasktemplate_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomtasktemplate',
            name='default_symptoms',
            field=models.ManyToManyField(blank=True, related_name='task_templates', to='core.Symptom'),
        ),
    ]
