# Generated by Django 2.0.7 on 2019-04-04 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_remove_teamtasktemplate_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttask',
            name='patient_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tasks', to='tasks.PatientTaskTemplate'),
        ),
        migrations.AlterField(
            model_name='symptomtask',
            name='symptom_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_tasks', to='tasks.SymptomTaskTemplate'),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='team_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='tasks.TeamTaskTemplate'),
        ),
    ]
