# Generated by Django 2.0.7 on 2019-04-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_auto_20190329_1509'),
        ('tasks', '0032_auto_20190404_0114'),
    ]

    operations = [
    ]
