# Generated by Django 2.0.7 on 2019-04-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0030_auto_20190327_1533'),
        ('tasks', '0033_merge_20190410_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlanPatientTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_start_on_day', models.IntegerField(blank=True, null=True)),
                ('custom_frequency', models.CharField(blank=True, choices=[('once', 'Once'), ('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], max_length=20)),
                ('custom_repeat_amount', models.IntegerField(blank=True, null=True)),
                ('custom_appear_time', models.TimeField(blank=True, null=True)),
                ('custom_due_time', models.TimeField(blank=True, null=True)),
                ('patient_task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_patient_templates', to='tasks.PatientTaskTemplate')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_patient_templates', to='plans.CarePlan')),
            ],
            options={
                'verbose_name': 'Care Plan Patient Templates',
            },
        ),
        migrations.AlterModelOptions(
            name='patienttask',
            options={'ordering': ('patient_template', 'due_datetime')},
        ),
        migrations.AddField(
            model_name='patienttask',
            name='patient_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.CarePlanPatientTemplate'),
        ),
    ]
