# Generated by Django 2.0.7 on 2019-04-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_auto_20190413_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttask',
            name='patient_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.CarePlanPatientTemplate'),
        ),
    ]
