# Generated by Django 2.0.7 on 2019-04-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_auto_20190413_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttask',
            name='patient_task_template',
        ),
        migrations.RemoveField(
            model_name='patienttask',
            name='plan',
        ),
    ]
