# Generated by Django 2.0.7 on 2019-04-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_careplansymptomtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomtask',
            name='symptom_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.CarePlanPatientTemplate'),
        ),
    ]
