# Generated by Django 2.0.7 on 2019-04-17 16:53

from django.db import migrations


def assign_plan_templates(apps, schema_editor):
    """
    This function will iterate over all :model:`tasks.SymptomTask`
    and do the following on each instance:

    - create CarePlanSymptomTemplate object based on plan and
        symptom_task_template
    - assign the created CarePlanSymptomTemplate object above into the
        symptom_template field
    """
    SymptomTask = apps.get_model('tasks', 'SymptomTask')
    CarePlanSymptomTemplate = apps.get_model('tasks',
                                             'CarePlanSymptomTemplate')
    for task in SymptomTask.objects.all():
        symptom_template = CarePlanSymptomTemplate.objects.create(
            plan=task.plan,
            symptom_task_template=task.symptom_task_template
        )

        task.symptom_template = symptom_template
        task.save(update_fields=['[symptom_template'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_symptomtask_symptom_template'),
    ]

    operations = [
        migrations.RunPython(assign_plan_templates)
    ]
