# Generated by Django 2.0.7 on 2019-04-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_auto_20190417_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptomtask',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='symptomtask',
            name='symptom_task_template',
        ),
        migrations.AlterField(
            model_name='symptomtask',
            name='symptom_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.CarePlanPatientTemplate'),
        ),
    ]
