# Generated by Django 2.0.7 on 2019-04-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_auto_20190417_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomtask',
            name='symptom_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.CarePlanSymptomTemplate'),
        ),
    ]
