# Generated by Django 2.0.7 on 2019-04-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_careplanteamtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtask',
            name='team_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.CarePlanTeamTemplate'),
        ),
    ]
