# Generated by Django 2.0.7 on 2019-04-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_teamtask_team_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careplanteamtemplate',
            old_name='symptom_task_template',
            new_name='team_task_template',
        ),
    ]
