# Generated by Django 2.0.7 on 2019-04-23 09:00

from django.db import migrations


def assign_plan_templates(apps, schema_editor):
    """
    This function will iterate over all :model:`tasks.TeamTask`
    and do the following on each instance:

    - create CarePlanTeamTemplate object based on plan and
        team_task_template
    - assign the created CarePlanTeamTemplate object above into the
        team_template field
    """
    TeamTask = apps.get_model('tasks', 'TeamTask')
    CarePlanTeamTemplate = apps.get_model('tasks',
                                          'CarePlanTeamTemplate')
    for task in TeamTask.objects.all():
        team_template = CarePlanTeamTemplate.objects.create(
            plan=task.plan,
            team_task_template=task.team_task_template
        )

        task.team_template = team_template
        task.save(update_fields=['[team_template'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0044_auto_20190423_0300'),
    ]

    operations = [
        migrations.RunPython(assign_plan_templates)
    ]
