# Generated by Django 2.0.7 on 2019-04-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0045_auto_20190423_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtask',
            options={'ordering': ('team_template', 'due_datetime')},
        ),
        migrations.RemoveField(
            model_name='teamtask',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='teamtask',
            name='team_task_template',
        ),
    ]
