# Generated by Django 2.0.7 on 2019-04-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_auto_20190423_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtask',
            name='team_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.CarePlanTeamTemplate'),
        ),
    ]
