# Generated by Django 2.0.7 on 2019-04-26 09:18

from django.db import migrations


def assign_plan_templates(apps, schema_editor):
    """
    This function will iterate over all :model:`tasks.AssessmentTask`
    and do the following on each instance:

    - create CarePlanAssessmentTemplate object based on plan and
        assessment_task_template
    - assign the created CarePlanAssessmentTemplate object above into the
        assessment_template field
    """
    AssessmentTask = apps.get_model('tasks', 'AssessmentTask')
    CarePlanAssessmentTemplate = apps.get_model('tasks',
                                                'CarePlanAssessmentTemplate')
    for task in AssessmentTask.objects.all():
        assessment_template = CarePlanAssessmentTemplate.objects.create(
            plan=task.plan,
            assessment_task_template=task.assessment_task_template
        )

        task.assessment_template = assessment_template
        task.save(update_fields=['[assessment_template'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_assessmenttask_assessment_template'),
    ]

    operations = [
        migrations.RunPython(assign_plan_templates)
    ]
