# Generated by Django 2.0.7 on 2019-04-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0050_auto_20190426_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttask',
            name='assessment_task_template',
        ),
        migrations.RemoveField(
            model_name='assessmenttask',
            name='plan',
        ),
    ]
