# Generated by Django 2.0.7 on 2019-04-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0051_auto_20190426_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttask',
            name='assessment_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.CarePlanAssessmentTemplate'),
        ),
    ]
