# Generated by Django 2.0.7 on 2019-04-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0052_auto_20190426_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttask',
            name='assessment_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_tasks', to='tasks.CarePlanAssessmentTemplate'),
        ),
    ]
