# Generated by Django 2.0.7 on 2019-05-03 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0057_auto_20190502_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitaltask',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='vitaltask',
            name='vital_task_template',
        ),
    ]
