# Generated by Django 2.0.7 on 2019-05-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0058_auto_20190502_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplanassessmenttemplate',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='careplanpatienttemplate',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='careplansymptomtemplate',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='careplanteamtemplate',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='careplanvitaltemplate',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
