# Generated by Django 2.0.7 on 2019-05-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_employeerole'),
        ('tasks', '0059_auto_20190512_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplansymptomtemplate',
            name='custom_default_symptoms',
            field=models.ManyToManyField(blank=True, related_name='plan_task_templates', to='core.Symptom'),
        ),
    ]
