# Generated by Django 2.0.7 on 2019-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0060_careplansymptomtemplate_custom_default_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplanvitaltemplate',
            name='custom_instructions',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
