# Generated by Django 2.0.7 on 2019-05-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0061_careplanvitaltemplate_custom_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplanassessmenttemplate',
            name='custom_tracks_outcome',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='careplanassessmenttemplate',
            name='custom_tracks_satisfaction',
            field=models.NullBooleanField(),
        ),
    ]
