# Generated by Django 2.0.7 on 2019-05-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0063_careplanteamtemplate_custom_is_manager_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplanteamtemplate',
            name='custom_category',
            field=models.CharField(blank=True, choices=[('notes', 'Notes'), ('interaction', 'Patient Interaction'), ('coordination', 'Care Team Coordination')], max_length=120),
        ),
    ]
