# Generated by Django 2.0.7 on 2019-06-02 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0032_careplanresultovertime'),
        ('tasks', '0065_careplanteamtemplate_custom_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='This will be used for ad hoc tasks.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='plans.CarePlan'),
        ),
    ]
