# Generated by Django 2.0.7 on 2019-06-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0067_vitalquestion_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='tasks.CarePlanAssessmentTemplate'),
        ),
    ]
