# Generated by Django 2.0.7 on 2019-06-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0069_auto_20190604_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='plan',
        ),
    ]
