# Generated by Django 2.0.7 on 2019-06-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0070_remove_assessmentquestion_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalquestion',
            name='vital_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_questions', to='tasks.CarePlanVitalTemplate'),
        ),
    ]
