# Generated by Django 2.0.7 on 2019-06-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0071_vitalquestion_vital_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalquestion',
            name='vital_task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tasks.VitalTaskTemplate'),
        ),
    ]
