# Generated by Django 2.0.7 on 2019-06-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0072_auto_20190604_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalquestion',
            name='plan',
        ),
    ]
