# Generated by Django 2.0.7 on 2019-06-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0074_auto_20190608_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttasktemplate',
            name='instructions',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='careplanassessmenttemplate',
            name='custom_instructions',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
