# Generated by Django 2.0.7 on 2019-07-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0075_auto_20190612_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitaltask',
            name='comments',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
