# Generated by Django 2.0.7 on 2018-09-11 00:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_remove_patientmedication_refills'),
        ('core', '0004_symptom'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_on_day', models.IntegerField()),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='once', max_length=20)),
                ('repeat_amount', models.IntegerField(default=-1, help_text="\n        Only matters if frequency is not 'once'.\n        If it is below 0, it will repeat until the plan ends\n        ")),
                ('appear_time', models.TimeField()),
                ('due_time', models.TimeField()),
                ('tracks_outcome', models.BooleanField(default=False)),
                ('tracks_satisfaction', models.BooleanField(default=False)),
                ('plan_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_tasks', to='plans.CarePlanTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationTaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appear_datetime', models.DateTimeField()),
                ('due_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('undefined', 'Undefined'), ('missed', 'Missed'), ('done', 'Done')], default='undefined', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_on_day', models.IntegerField()),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='once', max_length=20)),
                ('repeat_amount', models.IntegerField(default=-1, help_text="\n        Only matters if frequency is not 'once'.\n        If it is below 0, it will repeat until the plan ends\n        ")),
                ('appear_time', models.TimeField()),
                ('due_time', models.TimeField()),
                ('patient_medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientMedication')),
                ('plan_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.CarePlanInstance')),
            ],
            options={
                'ordering': ('plan_instance', 'patient_medication'),
            },
        ),
        migrations.CreateModel(
            name='PatientTaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appear_datetime', models.DateTimeField()),
                ('due_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('undefined', 'Undefined'), ('missed', 'Missed'), ('done', 'Done')], default='undefined', max_length=12)),
            ],
            options={
                'ordering': ('plan_instance', 'patient_task_template', 'due_datetime'),
            },
        ),
        migrations.CreateModel(
            name='PatientTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_on_day', models.IntegerField()),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='once', max_length=20)),
                ('repeat_amount', models.IntegerField(default=-1, help_text="\n        Only matters if frequency is not 'once'.\n        If it is below 0, it will repeat until the plan ends\n        ")),
                ('appear_time', models.TimeField()),
                ('due_time', models.TimeField()),
                ('name', models.CharField(max_length=140)),
                ('plan_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tasks', to='plans.CarePlanTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Symptom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomTaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appear_datetime', models.DateTimeField()),
                ('due_datetime', models.DateTimeField()),
                ('comments', models.CharField(max_length=1024)),
                ('plan_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.CarePlanInstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_on_day', models.IntegerField()),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='once', max_length=20)),
                ('repeat_amount', models.IntegerField(default=-1, help_text="\n        Only matters if frequency is not 'once'.\n        If it is below 0, it will repeat until the plan ends\n        ")),
                ('appear_time', models.TimeField()),
                ('due_time', models.TimeField()),
                ('plan_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_tasks', to='plans.CarePlanTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamTaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appear_datetime', models.DateTimeField()),
                ('due_datetime', models.DateTimeField()),
                ('plan_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.CarePlanInstance')),
            ],
            options={
                'ordering': ('plan_instance', 'team_task_template', 'due_datetime'),
            },
        ),
        migrations.CreateModel(
            name='TeamTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_on_day', models.IntegerField()),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='once', max_length=20)),
                ('repeat_amount', models.IntegerField(default=-1, help_text="\n        Only matters if frequency is not 'once'.\n        If it is below 0, it will repeat until the plan ends\n        ")),
                ('appear_time', models.TimeField()),
                ('due_time', models.TimeField()),
                ('name', models.CharField(max_length=140)),
                ('is_manager_task', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('notes', 'Notes'), ('interaction', 'Patient Interaction'), ('coordination', 'Care Team Coordination')], max_length=120)),
                ('plan_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='plans.CarePlanTemplate')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProviderRole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teamtaskinstance',
            name='team_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.TeamTaskTemplate'),
        ),
        migrations.AddField(
            model_name='symptomtaskinstance',
            name='symptom_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.SymptomTaskTemplate'),
        ),
        migrations.AddField(
            model_name='symptomrating',
            name='symptom_task_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.SymptomTaskInstance'),
        ),
        migrations.AddField(
            model_name='patienttaskinstance',
            name='patient_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.PatientTaskTemplate'),
        ),
        migrations.AddField(
            model_name='patienttaskinstance',
            name='plan_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.CarePlanInstance'),
        ),
        migrations.AddField(
            model_name='medicationtaskinstance',
            name='medication_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.MedicationTaskTemplate'),
        ),
    ]
