# Generated by Django 2.0.7 on 2018-09-11 00:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=240)),
                ('worst_label', models.CharField(max_length=40)),
                ('best_label', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.AssessmentQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentTaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appear_datetime', models.DateTimeField()),
                ('due_datetime', models.DateTimeField()),
                ('comments', models.CharField(max_length=1024)),
                ('plan_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.CarePlanInstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessmenttasktemplate',
            name='name',
            field=models.CharField(default='Depression assessment', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='assessment_task_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.AssessmentTaskInstance'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.AssessmentTaskTemplate'),
        ),
    ]
