# Generated by Django 2.0.7 on 2018-09-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180912_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtask',
            name='status',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('missed', 'Missed'), ('done', 'Done')], default='undefined', max_length=12),
        ),
    ]
