# Generated by Django 2.0.7 on 2018-09-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_teamtask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentresponse',
            options={'ordering': ('assessment_task__appear_datetime',)},
        ),
        migrations.AlterModelOptions(
            name='assessmenttask',
            options={'ordering': ('appear_datetime',)},
        ),
        migrations.AlterModelOptions(
            name='medicationtask',
            options={'ordering': ('appear_datetime',)},
        ),
        migrations.AlterModelOptions(
            name='symptomtask',
            options={'ordering': ('appear_datetime',)},
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False, help_text='Set to True if all questions has its corresponding response.'),
        ),
    ]
