# Generated by Django 2.0.7 on 2018-09-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20180917_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomtask',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False, help_text='Set to True if a rating has been created for this symptom task.'),
        ),
    ]
