# Generated by Django 2.0.7 on 2018-09-18 05:51

from django.db import migrations


def assign_is_complete_to_symptom_tasks(apps, schema_editor):
    """
    This migration will run through all SymptomTask and set the `is_complete`
    field of :model:`tasks.AssesmentTask` to True if all at least one
    SymptomRating was created for each of the corresponding SymptomTask.
    """
    SymptomTask = apps.get_model('tasks', 'SymptomTask')

    for task in SymptomTask.objects.all():
        if task.symptomrating_set.exists():
            task.is_complete = True
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_symptomtask_is_complete'),
    ]

    operations = [
        migrations.RunPython(assign_is_complete_to_symptom_tasks)
    ]
