# Generated by Django 2.0.7 on 2018-09-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180917_1316'),
        ('tasks', '0009_auto_20180917_2351'),
    ]

    operations = [
    ]
