# Generated by Django 2.0.7 on 2018-09-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20180923_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestion',
            name='assessment_task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tasks.AssessmentTaskTemplate'),
        ),
    ]
