# Generated by Django 2.0.7 on 2018-09-25 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20180924_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresponse',
            name='assessment_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tasks.AssessmentTask'),
        ),
    ]
