# Generated by Django 2.0.7 on 2018-09-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20180924_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalquestion',
            name='answer_type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('time', 'Time'), ('float', 'Float'), ('integer', 'Integer'), ('scale', 'Scale'), ('string', 'String')], max_length=128),
        ),
    ]
