# Generated by Django 2.0.7 on 2018-10-06 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20181004_1930'),
        ('patients', '0006_merge_20181005_1359'),
    ]

    operations = [
    ]
