# Generated by Django 2.0.7 on 2018-10-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_merge_20181005_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderemail',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_emails', to='patients.PatientProfile'),
        ),
    ]
