# Generated by Django 2.0.7 on 2018-10-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20181008_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
