# Generated by Django 2.0.7 on 2018-10-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20181017_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='status',
        ),
    ]
