# Generated by Django 2.0.7 on 2018-10-19 02:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20181005_1359'),
        ('patients', '0010_remove_patientprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialPatient',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('care_plan', models.CharField(max_length=64, verbose_name='Care plan')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone number')),
                ('facility', models.ManyToManyField(blank=True, to='core.Facility')),
                ('patient_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.PatientProfile')),
            ],
            options={
                'verbose_name': 'Potential Patient',
                'verbose_name_plural': 'Potential Patients',
            },
        ),
    ]
