# Generated by Django 2.0.7 on 2018-10-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_potentialpatient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potentialpatient',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Potential Patient', 'verbose_name_plural': 'Potential Patients'},
        ),
    ]
