# Generated by Django 2.0.7 on 2019-02-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patientprofile_last_app_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='payer_reimbursement',
            field=models.BooleanField(default=False, help_text='Used to determine whether a patient is billable or not.'),
        ),
    ]
