# Generated by Django 2.0.7 on 2019-02-15 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patientprofile_payer_reimbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStat',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mrn', models.CharField(max_length=20)),
                ('readmissions_count', models.IntegerField()),
                ('readmissions_percent', models.FloatField()),
                ('readmissions_cost', models.FloatField()),
                ('ed_visits', models.IntegerField()),
                ('opioid_use', models.IntegerField()),
                ('admits', models.IntegerField()),
                ('avg_stay_length', models.FloatField()),
                ('pcp_visits', models.IntegerField()),
                ('specialist_visits', models.IntegerField()),
                ('total_cost', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
