# Generated by Django 2.0.7 on 2019-02-14 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patientprofile_payer_reimbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('readmissions_count', models.IntegerField()),
                ('readmissions_percent', models.FloatField()),
                ('readmissions_cost', models.FloatField()),
                ('ed_visits', models.IntegerField()),
                ('opioid_use', models.IntegerField()),
                ('admits', models.IntegerField()),
                ('avg_stay_length', models.FloatField()),
                ('pcp_visits', models.IntegerField()),
                ('specialist_visits', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_stat', to='patients.PatientProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
