# Generated by Django 2.0.7 on 2019-02-13 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patientprofile_payer_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='risk_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
