# Generated by Django 2.0.7 on 2019-02-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_patientstat'),
        ('patients', '0015_patientprofile_risk_level'),
    ]

    operations = [
    ]
