# Generated by Django 2.0.7 on 2019-02-19 13:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_billingcoordinator'),
        ('patients', '0016_merge_20190215_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('relationship', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(max_length=16, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ('patient', 'created'),
            },
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='addr_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='addr_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='addr_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='addr_suite',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='addr_zip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='cognitive_ability',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=64),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='communication_preference',
            field=models.CharField(choices=[('phone', 'Phone'), ('text_message', 'Text Message'), ('in_app_messaging', 'In-App Messaging')], default='phone', max_length=64),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height_feet',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height_inches',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to='core.Insurance'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='mrn',
            field=models.CharField(blank=True, help_text='When provided, this should be unique.', max_length=64),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='secondary_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_patients', to='core.Insurance'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='source',
            field=models.CharField(blank=True, choices=[('analytics_app', 'Analytics App'), ('md_request', 'MD Request'), ('care_team_request', 'Care Team Request'), ('care_manager', 'Care Manager')], max_length=64),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telemedicine',
            field=models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('not_applicable', 'Not Applicable')], default='interested', max_length=64),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.PatientProfile'),
        ),
    ]
