# Generated by Django 2.0.7 on 2019-02-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20190219_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialpatient',
            name='care_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_patients', to='plans.CarePlanTemplate'),
        ),
    ]
