# Generated by Django 2.0.7 on 2019-02-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0027_careplan_is_active'),
        ('patients', '0017_auto_20190219_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemarea',
            name='plan',
            field=models.ForeignKey(default='fdb25787-150f-4117-a757-b1cd399b98f3', on_delete=django.db.models.deletion.CASCADE, related_name='problem_areas', to='plans.CarePlan'),
            preserve_default=False,
        ),
    ]
