# Generated by Django 2.0.7 on 2019-02-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_auto_20190222_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialpatient',
            name='source',
            field=models.CharField(default='Local', max_length=256, verbose_name='Source'),
            preserve_default=False,
        ),
    ]
