# Generated by Django 2.0.7 on 2019-02-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_potentialpatient_source'),
        ('patients', '0018_problemarea_plan'),
    ]

    operations = [
    ]
