# Generated by Django 2.0.7 on 2019-02-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_merge_20190225_1323'),
        ('patients', '0020_merge_20190225_1401'),
    ]

    operations = [
    ]
