# Generated by Django 2.0.7 on 2019-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_problemarea_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
