# Generated by Django 2.0.7 on 2019-03-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_problemarea_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialpatient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
