# Generated by Django 2.0.7 on 2019-03-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_patientprofile_is_archived'),
        ('patients', '0023_potentialpatient_email'),
    ]

    operations = [
    ]
