# Generated by Django 2.0.7 on 2019-03-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_merge_20190313_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiagnosis',
            name='is_chronic',
            field=models.BooleanField(default=False),
        ),
    ]
