# Generated by Django 2.0.7 on 2019-03-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_patientprofile_is_using_mobile'),
        ('patients', '0025_patientdiagnosis_is_chronic'),
    ]

    operations = [
    ]
