# Generated by Django 2.0.7 on 2019-03-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_merge_20190320_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='communication_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
