# Generated by Django 2.0.7 on 2019-04-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_patientprofile_communication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='emails_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
