# Generated by Django 2.0.7 on 2019-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_patientprofile_emails_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
