# Generated by Django 2.0.7 on 2019-05-09 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_auto_20190424_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectivePatient',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mrn', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Phone number')),
                ('enhnicity', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosises', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('procedures', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
