# Generated by Django 2.0.7 on 2018-10-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailuser_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
