# Generated by Django 2.0.7 on 2019-02-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190223_0921'),
        ('accounts', '0007_auto_20190223_1157'),
    ]

    operations = [
    ]
