# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-21 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('dx_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('addr_street', models.CharField(blank=True, max_length=255, null=True)),
                ('addr_suite', models.CharField(blank=True, max_length=35, null=True)),
                ('addr_city', models.CharField(blank=True, max_length=255, null=True)),
                ('addr_state', models.CharField(blank=True, max_length=255, null=True)),
                ('addr_zip', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(max_length=120)),
                ('is_affiliate', models.BooleanField(default=False)),
                ('parent_company', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('addr_street', models.CharField(blank=True, max_length=255, null=True)),
                ('addr_suite', models.CharField(blank=True, max_length=35, null=True)),
                ('addr_city', models.CharField(blank=True, max_length=255, null=True)),
                ('addr_state', models.CharField(blank=True, max_length=255, null=True)),
                ('addr_zip', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facilities', models.ManyToManyField(blank=True, related_name='providers', to='core.Facility')),
                ('facilities_managed', models.ManyToManyField(blank=True, related_name='managers', to='core.Facility')),
                ('organizations', models.ManyToManyField(related_name='providers', to='core.Organization')),
                ('organizations_managed', models.ManyToManyField(blank=True, related_name='managers', to='core.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderSpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('physician_specialty', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='roles',
            field=models.ManyToManyField(to='core.ProviderRole'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProviderSpecialty'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProviderTitle'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
    ]
