# Generated by Django 2.0.7 on 2018-07-31 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.ProviderRole'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ProviderSpecialty'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ProviderTitle'),
        ),
    ]
