# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-21 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180621_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'diagnosis'},
        ),
        migrations.AlterModelOptions(
            name='providerspecialty',
            options={'verbose_name_plural': 'provider specialties'},
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='providers', to='core.Organization'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProviderSpecialty'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProviderTitle'),
        ),
    ]
