# Generated by Django 2.0.7 on 2018-09-10 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeeprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('worst_label', models.CharField(help_text='\n    This is the label that will show on symptom reports at the 1 position.  For example\n    for the fatigue symptom that could be "very fatigued".\n    ', max_length=40)),
                ('best_label', models.CharField(help_text='\n    Same as the worst label, but this will show at the 5 position.  For example\n    for the fatigue symptom that could be "no fatigue".\n    ', max_length=40)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
