# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-29 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180628_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('px_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='name',
            field=models.CharField(default='Heh', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='rx_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
