# Generated by Django 2.0.7 on 2018-10-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181002_0641'),
        ('core', '0005_invitedemailtemplate'),
    ]

    operations = [
    ]
