# Generated by Django 2.0.7 on 2018-07-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180731_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('inactive', 'Inactive'), ('active', 'Active')], default='invited', max_length=20),
        ),
    ]
