# Generated by Django 2.0.7 on 2018-10-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_symptom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ('name', 'organization'), 'verbose_name_plural': 'facilities'},
        ),
    ]
