# Generated by Django 2.0.7 on 2018-10-04 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedEmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='Invitation to CareAdopt', max_length=140)),
                ('message', models.CharField(max_length=500)),
                ('is_default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
