# Generated by Django 2.0.7 on 2019-02-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190126_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='billing_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='qualified_practitioner',
            field=models.BooleanField(default=False),
        ),
    ]
