# Generated by Django 2.0.7 on 2019-02-12 09:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190212_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCoordinator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_coordinators_for', to='core.EmployeeProfile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_coordinators', to='core.EmployeeProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
