# Generated by Django 2.0.7 on 2019-03-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_billingcoordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='available_users',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
