# Generated by Django 2.0.7 on 2018-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.IntegerField(default=1),
        ),
    ]
