# Generated by Django 2.0.7 on 2018-09-13 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patientmedication_refills'),
        ('tasks', '0003_assessmenttaskinstance_assessment_task_template'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarePlanInstance',
            new_name='CarePlan',
        ),
        migrations.RenameField(
            model_name='careteammember',
            old_name='plan_instance',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='planconsent',
            old_name='plan_instance',
            new_name='plan',
        ),
    ]
