# Generated by Django 2.0.7 on 2018-08-15 10:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeeprofile_status'),
        ('plans', '0002_goal_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStream',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('start_on_day', models.IntegerField()),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='once', max_length=20)),
                ('repeat_amount', models.IntegerField(default=-1)),
                ('appear_time', models.TimeField()),
                ('due_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teamtask',
            name='is_manager_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProviderRole'),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='category',
            field=models.CharField(choices=[('notes', 'Notes'), ('interaction', 'Patient Interaction'), ('coordination', 'Care Team Coordination')], max_length=120),
        ),
        migrations.AddField(
            model_name='careplantemplate',
            name='message_streams',
            field=models.ManyToManyField(blank=True, to='plans.MessageStream'),
        ),
    ]
