# Generated by Django 2.0.7 on 2018-09-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20180912_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplantemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
