# Generated by Django 2.0.7 on 2018-09-19 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20180912_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='plans.GoalTemplate')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='plans.CarePlan')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ('created',),
            },
        ),
    ]
