# Generated by Django 2.0.7 on 2018-08-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20180815_0413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planconsent',
            options={'ordering': ('created',)},
        ),
    ]
