# Generated by Django 2.0.7 on 2018-08-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20180815_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='duration_weeks',
            field=models.IntegerField(default=1, help_text='If below 0, the goal will continue until the plan ends.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='start_on_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patienttask',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('every_other_day', 'Every Other Day'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='once', max_length=20),
        ),
        migrations.AlterField(
            model_name='patienttask',
            name='repeat_amount',
            field=models.IntegerField(default=-1, help_text="\n        Only matters if frequency is not 'once'.\n        If it is below 0, it will repeat until the plan ends\n        "),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='once', max_length=20),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='repeat_amount',
            field=models.IntegerField(default=-1, help_text="\n        Only matters if frequency is not 'once'.\n        If it is below 0, it will repeat until the plan ends\n        "),
        ),
    ]
