# Generated by Django 2.0.7 on 2018-09-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_careplantemplate_is_active'),
        ('plans', '0005_goalcomment'),
    ]

    operations = [
    ]
