# Generated by Django 2.0.7 on 2018-09-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_merge_20180921_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careplan',
            name='plan_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='plans.CarePlanTemplate'),
        ),
    ]
