# Generated by Django 2.0.7 on 2018-08-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20180827_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomessage',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='plans.InfoMessageQueue'),
        ),
    ]
