# Generated by Django 2.0.7 on 2018-08-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeeprofile_status'),
        ('plans', '0008_auto_20180827_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goal',
            new_name='GoalTemplate',
        ),
        migrations.RenameModel(
            old_name='PatientTask',
            new_name='PatientTaskTemplate',
        ),
        migrations.RenameModel(
            old_name='TeamTask',
            new_name='TeamTaskTemplate',
        ),
    ]
