# Generated by Django 2.0.7 on 2018-08-29 06:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeeprofile_status'),
        ('plans', '0009_auto_20180827_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_roles', to='core.EmployeeProfile')),
                ('plan_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team_members', to='plans.CarePlanInstance')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProviderRole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientTaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.PatientTaskTemplate')),
                ('plan_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.CarePlanInstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='goaltemplate',
            name='progress',
        ),
    ]
