# Generated by Django 2.0.7 on 2019-01-28 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_merge_20181005_1359'),
        ('plans', '0018_auto_20190125_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilledActivity',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('care_plan_review', 'Care Plan Review'), ('phone_call', 'Phone Call'), ('notes', 'Notes'), ('face_to_face', 'Face to Face'), ('message', 'Message')], default='care_plan_review', max_length=32)),
                ('sync_to_ehr', models.BooleanField(default=False)),
                ('activity_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('time_spent', models.PositiveIntegerField(help_text='in minutes')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_activities', to='core.EmployeeProfile')),
                ('members', models.ManyToManyField(related_name='activities', to='core.EmployeeProfile')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='plans.CarePlan')),
            ],
            options={
                'verbose_name': 'Billed Activity',
                'verbose_name_plural': 'Billed Activities',
                'ordering': ('-created',),
            },
        ),
    ]
