# Generated by Django 2.0.7 on 2019-02-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billedactivity',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='activities', to='core.EmployeeProfile'),
        ),
    ]
