# Generated by Django 2.0.7 on 2019-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_auto_20190208_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='billedactivity',
            name='is_billed',
            field=models.BooleanField(default=False, help_text='Determines if the instance has been billed externally.'),
        ),
    ]
