# Generated by Django 2.0.7 on 2019-02-19 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20190124_2104'),
        ('billings', '0003_billedactivity_is_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='billedactivity',
            name='team_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.TeamTask'),
        ),
    ]
