# Generated by Django 2.0.7 on 2019-03-07 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_billedactivity_team_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('acronym', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Billing Type',
                'verbose_name_plural': 'Billing Types',
                'ordering': ('-created',),
            },
        ),
    ]
