# Generated by Django 2.0.7 on 2019-03-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_billingtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingtype',
            options={'ordering': ('-name',), 'verbose_name': 'Billing Type', 'verbose_name_plural': 'Billing Types'},
        ),
        migrations.AddField(
            model_name='billingtype',
            name='billable_minutes',
            field=models.PositiveIntegerField(default=30, help_text='The amount of minutes per month that can be billed for care plans under this type'),
        ),
    ]
