# Generated by Django 2.0.7 on 2019-03-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0006_auto_20190308_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingtype',
            options={'ordering': ('name',), 'verbose_name': 'Billing Type', 'verbose_name_plural': 'Billing Types'},
        ),
    ]
