# Generated by Django 2.0.7 on 2019-03-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0007_auto_20190312_1137'),
        ('billings', '0007_auto_20190312_0319'),
    ]

    operations = [
    ]
