# Generated by Django 2.0.7 on 2019-03-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0008_merge_20190313_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billedactivity',
            options={'ordering': ('-activity_date',), 'verbose_name': 'Billed Activity', 'verbose_name_plural': 'Billed Activities'},
        ),
        migrations.AddField(
            model_name='billedactivity',
            name='patient_included',
            field=models.BooleanField(default=False, help_text='Determines if the activity included the patient.'),
        ),
    ]
