# Generated by Django 2.0.7 on 2019-03-16 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_merge_20190311_0500'),
        ('billings', '0009_auto_20190315_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billedactivity',
            options={'ordering': ('-activity_datetime',), 'verbose_name': 'Billed Activity', 'verbose_name_plural': 'Billed Activities'},
        ),
        migrations.RemoveField(
            model_name='billedactivity',
            name='activity_date',
        ),
        migrations.RemoveField(
            model_name='billedactivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='billedactivity',
            name='team_task',
        ),
        migrations.AddField(
            model_name='billedactivity',
            name='activity_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='billedactivity',
            name='team_task_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.TeamTaskTemplate'),
        ),
    ]
