# Generated by Django 2.0.7 on 2019-04-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0010_auto_20190316_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billedactivity',
            name='team_task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.TeamTaskTemplate'),
        ),
    ]
