# Generated by Django 2.0.7 on 2019-06-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0074_auto_20190608_0849'),
        ('billings', '0011_auto_20190410_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='billedactivity',
            name='team_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.CarePlanTeamTemplate'),
        ),
    ]
