# Generated by Django 2.0.7 on 2019-06-10 06:59

from django.db import migrations


def assign_team_templates_in_billed_activity(apps, schema_editor):
    """
    This function will iterate over all :model:`billings.BilledActivity`
    and do the following on each instance:

    - get or create CarePlanTeamTemplate object based on plan and
        team_task_template
    - assign the created CarePlanTeamTemplate object above into the
        team_template field
    """
    BilledActivity = apps.get_model('billings', 'BilledActivity')
    CarePlanTeamTemplate = apps.get_model('tasks',
                                          'CarePlanTeamTemplate')
    for billing in BilledActivity.objects.all():
        team_template, created = CarePlanTeamTemplate.objects.get_or_create(
            plan=billing.plan,
            team_task_template=billing.team_task_template
        )

        billing.team_template = team_template
        billing.save(update_fields=['team_template'])


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0012_billedactivity_team_template'),
    ]

    operations = [
        migrations.RunPython(assign_team_templates_in_billed_activity)
    ]
