# Generated by Django 2.0.7 on 2018-09-19 05:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='plans.Goal')),
            ],
            options={
                'verbose_name': 'Goal Progress',
                'verbose_name_plural': 'Goal Progresses',
                'ordering': ('created',),
            },
        ),
    ]
