# Generated by Django 2.0.7 on 2018-09-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20180925_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='start_on_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
