# Generated by Django 2.0.7 on 2018-09-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_goal_start_on_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_on_datetime',
            field=models.DateTimeField(),
        ),
    ]
