# Generated by Django 2.0.7 on 2018-10-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_careteammember_is_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalcomment',
            options={'ordering': ('-created',), 'verbose_name': 'Goal Comment', 'verbose_name_plural': 'Goal Comments'},
        ),
    ]
