# Generated by Django 2.0.7 on 2018-10-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_careplantemplatetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careplantemplate',
            name='type',
        ),
    ]
