# Generated by Django 2.0.7 on 2018-10-26 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_remove_careplantemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplantemplate',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_templates', to='plans.CarePlanTemplateType'),
        ),
    ]
