# Generated by Django 2.0.7 on 2019-01-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_auto_20181212_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careteammember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProviderRole'),
        ),
    ]
