# Generated by Django 2.0.7 on 2019-01-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_auto_20181212_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careplantemplate',
            options={'ordering': ('-created',)},
        ),
    ]
