# Generated by Django 2.0.7 on 2019-01-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_auto_20190104_2102'),
        ('plans', '0016_auto_20190104_0302'),
    ]

    operations = [
    ]
