# Generated by Django 2.0.7 on 2019-01-26 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0017_merge_20190119_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomessage',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
