# Generated by Django 2.0.7 on 2019-02-03 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0019_messagerecipient_teammessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecipient',
            name='members',
            field=models.ManyToManyField(related_name='message_recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
