# Generated by Django 2.0.7 on 2019-02-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190126_0640'),
        ('plans', '0020_auto_20190202_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='billing_practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EmployeeProfile'),
        ),
    ]
