# Generated by Django 2.0.7 on 2019-02-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0021_careplan_billing_practitioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careplan',
            name='billing_practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billed_plans', to='core.EmployeeProfile'),
        ),
    ]
