# Generated by Django 2.0.7 on 2019-02-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0023_careplan_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='next_checkin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
