# Generated by Django 2.0.7 on 2019-02-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0024_careplan_next_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='is_billed',
            field=models.BooleanField(default=False, editable=False, help_text='Determines if all BilledActivity of this instance has been billed'),
        ),
    ]
