# Generated by Django 2.0.7 on 2019-03-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_billingtype'),
        ('plans', '0027_careplan_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careplantemplate',
            name='type',
        ),
        migrations.AddField(
            model_name='careplan',
            name='billing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='billings.BillingType'),
        ),
        migrations.DeleteModel(
            name='CarePlanTemplateType',
        ),
    ]
