# Generated by Django 2.0.7 on 2019-03-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0029_auto_20190321_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomessagequeue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='infomessagequeue',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
