# Generated by Django 2.0.7 on 2019-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0030_auto_20190327_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_messages'),
        ),
    ]
