# Generated by Django 2.0.7 on 2019-05-04 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0031_teammessage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlanResultOverTime',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.IntegerField()),
                ('engagement', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_over_time', to='plans.CarePlan')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
