# Generated by Django 2.0.7 on 2018-09-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientmedication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedication',
            name='refills',
        ),
    ]
