# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-28 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20180621_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnosis',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientProfile'),
        ),
    ]
