# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-29 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180629_1616'),
        ('patients', '0004_auto_20180628_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_procedure', models.DateField(blank=True, null=True)),
                ('attending_practitioner', models.CharField(blank=True, max_length=140, null=True)),
                ('facility', models.CharField(blank=True, max_length=140, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='patient',
        ),
        migrations.AddField(
            model_name='problemarea',
            name='date_identified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.AddField(
            model_name='patientprocedure',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Procedure'),
        ),
    ]
