# Generated by Django 2.0.7 on 2018-10-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_reminderemail'),
        ('patients', '0005_auto_20181003_2138'),
    ]

    operations = [
    ]
